/*
 * Copyright (c) 2020-2025.
 * The Android Open Source Project, valo.media GmbH
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import java.util.Properties

plugins {
    alias(libs.plugins.gradle.versions)
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.kotlin.parcelize) apply false
    alias(libs.plugins.compose) apply false
}

tasks.wrapper {
    // Use the gradle version pinned in gradle/wrapper/gradle-wrapper.properties.
    //
    // That file is the single source of truth for the gradle version, and the only wrapper file
    // that is checked in: it is plain text, so it stays reviewable, and renovate keeps it fresh
    // through its gradle-wrapper manager. The wrapper jar and scripts stay untracked and are
    // regenerated by this task.
    //
    // This task is pulled in as a dependency by :app:preBuild, to ensure the wrapper is always
    // up-to-date with the desired version of gradle. Deriving the version here rather than
    // hard-coding it keeps that regeneration from silently re-pinning gradle to whichever
    // version happens to be running the task.
    val wrapperProperties = file("gradle/wrapper/gradle-wrapper.properties")
    val distributionUrl = wrapperProperties
        .takeIf { it.isFile }
        ?.let { file -> Properties().apply { file.reader().use(::load) } }
        ?.getProperty("distributionUrl")
        ?: error("$wrapperProperties must exist and define distributionUrl.")
    val distribution = Regex("""gradle-(.+?)-(bin|all)\.zip""").find(distributionUrl)
        ?: error("Cannot read the gradle version from distributionUrl: $distributionUrl")
    gradleVersion = distribution.groupValues[1]
    distributionType = when (distribution.groupValues[2]) {
        "all" -> Wrapper.DistributionType.ALL
        else -> Wrapper.DistributionType.BIN
    }
}
